# Generated by Django 4.0.4 on 2022-07-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product imeges'},
        ),
    ]
