# Generated by Django 2.2.14 on 2022-07-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220717_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
